### ISSUE TITLE
Customer using CSB on AWS deployed Postgress.  CSB failing to provide  VCAP user the required permission to administer the database.  

### ISSUE THREAD

**Issue by arulvannala** [cloudfoundry-incubator/csb-brokerpak-aws#10]
The vcap user which is created by the tile does not own ALL permission to Postgress Database that is created by CSB service. Due to this schema creation fails after the DB is created. I understand that these can be granted by admin level user of the Database(which is a manual step required to workaround this issue)   The customer was using the AWS service broker tile before which provided the  ALL  required permission by default when a database is created. 

https://vmware.slack.com/archives/CQ9TVL7KN/p1614606442039600

**Comment by sathishvenkataraman** [comment]
@arulvannala  this is a very serious issue for us in using the broker service.  I have already escalated this to you couple of weeks back, can you please help in getting this fixed ASAP?

**Comment by erniebilling** [comment]
I'm currently looking into this problem. Could you provide a code sample (maybe a simple cf pushable app) that demonstrates the problem. We'd like to make sure the fix addresses the issue.

**Comment by winnab** [comment]
Released in https://github.com/cloudfoundry-incubator/csb-brokerpak-aws/releases/tag/1.0.2-aws
