### ISSUE TITLE
Broker doesn't permit the role to access the custom schema created by the different role

### ISSUE THREAD

**Issue by chandan-prakash** [cloudfoundry-incubator/csb-brokerpak-aws#101]
**Describe the bug**
In one of the environment we observed that when an application is bind to the postgress service, application is able to create the custom multiple schema and perform all DB operations. But when the service is unbind and bind to the application , then credentials are rotated and with these new set of credentials application is failing to access the schema, results in permission denied.

**To Reproduce**
1. Bind service to application, (application creates custom multiple schema, with the flyway migration)
2. Unbind the service.
3. Bind the service to application again. (On this step, credentials get rotated and new credentials are issued to application)
4. Application fails to access the schema.

**Expected behavior**
Application should be able to access the custom schema, inspite of credentials are rotated.

**Additional context**
After some analysis we observed that in earlier version of broker, all the roles were member of binding_group. We had the flyway script, in that we had sql query which would set the owner to binding_group. With this change we were able to access the schema from application inspite of credentials are rotated. In the latest version of broker, the roles are not member of any of the group and also there is no role binding_group.

**Comment by FelisiaM** [comment]
Hi @chandan-prakash 

Thanks for raising this. 
We understand that this is new behaviour for this broker and the current recommendation is to continue using the old AWS broker which now has extended support.

Thanks, 
Felisia
