### ISSUE TITLE
[BUG] The cloud-service-broker-aws-1.0.1 logs passwords in plain text.

### ISSUE THREAD

**Issue by pivotal-asim-shaikh** [cloudfoundry-incubator/csb-brokerpak-aws#5]
## Description
The cloud-service-broker-aws-1.0.1 logs passwords in plain text.

## Expected Behavior
Passwords should be obfuscated.

## Actual Behavior
Snippet from log (I've replace the password with PLAINTEXTPASSWORD):
`Apply complete! Resources: 3 added, 0 changed, 0 destroyed.\n\nOutputs:\n\nhostname = csb-postgresql-55433951-ba33-4fae-aa93-7bc80835a025.cgfksd50wmdy.us-east-1.rds.amazonaws.com\nname = vsbdb\npassword = PLAINTEXTPASSWORD\nport = 5432\nstatus = created db vsbdb (id: csb-postgresql-55433951-ba33-4fae-aa93-7bc80835a025) on server csb-postgresql-55433951-ba33-4fae-aa93-7bc80835a025.cgfksd50wmdy.us-east-1.rds.amazonaws.com URL: https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#database:id=csb-postgresql-55433951-ba33-4fae-aa93-7bc80835a025;is-cluster=false\nuse_tls = true\nusername = SHiFbgscXWXZMQCI\n"}}`

## Steps to Reproduce

1. Create a service such as Postgres
2.Look at the logs in the cloud-service-broker-aws-1.0.1 application in the system org
3.
4.

## Your Environment

* Version used: OpsManager 2.10.3 TAS 2.10.8
* Operating System and version (desktop):
* Link to your project (if public):
* Platform (Azure/AWS/GCP): AWS
* Applicable Services:

**Comment by omerbensaadon** [comment]
@erniebilling has this been fixed? 

CC: @winnab @pivotal-marcela-campo

**Comment by erniebilling** [comment]
@omerbensaadon This has been fixed in the broker, but there has not been a release of the aws tile that includes the fix yet.

**Comment by winnab** [comment]
Fixed in https://github.com/cloudfoundry-incubator/csb-brokerpak-aws/releases/tag/1.0.2-aws and a new tile has been cut
